spring.application.name=status-service
server.port=8083

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.rabbitmq.template.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2s
spring.rabbitmq.listener.simple.retry.max-attempts=5

management.endpoints.web.exposure.include=health
