spring.application.name=shop-service
server.port=8082

spring.datasource.url=jdbc:postgresql://db:5432/online_store
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.rabbitmq.template.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2s
spring.rabbitmq.listener.simple.retry.max-attempts=5

store.service.url=http://store:8081

management.endpoints.web.exposure.include=health
